Repository moondance-labs/tanssi-symbiotic, pull requests merged in 2025-07, with the labels that each got.

#127 [MD-1185] - Create test that proves if operator is unregistered no vaults are shown in the past
  test/integration/Middleware.t.sol
Labels: D3-trivial, not-breaking

#129 Adds Changelog section for v1.1.1.
  CHANGELOG.md
Labels: D3-trivial, not-breaking

#124 Initial CL Optimization version
  demos/Demo.s.sol
  src/contracts/middleware/Middleware.sol
  src/contracts/middleware/MiddlewareStorage.sol
  src/contracts/middleware/OBaseMiddlewareReader.sol
  src/contracts/rewarder/ODefaultOperatorRewards.sol
  src/interfaces/middleware/IMiddleware.sol
  src/interfaces/middleware/IOBaseMiddlewareReader.sol
  test/fork/mainnet/Full.t.sol
  test/integration/Full.t.sol
  test/integration/Middleware.t.sol
  test/unit/DeployProduction.t.sol
  test/unit/Middleware.t.sol
Labels: breaking, D5-nicetohaveaudit⚠️

#131 Improvements on makefile, fix operator rewards PROXY name and added more functions to make easier the deployment
  Makefile
  deployment-docs/upgrade-docs/Dancelight.env
  deployment-docs/upgrade-docs/Stagelight.env
  deployment-docs/upgrade-docs/Tanssi.env
  script/DeployRewards.s.sol
  script/DeployTanssiEcosystem.s.sol
  test/unit/Deploy.t.sol
  upgrade-docs/2025-04-24.md
Labels: D3-trivial, not-breaking

#134 [MD-1150] [L-25] performUpkeep() may exceed Chainlink's maxPerformDataSize
  test/integration/Middleware.t.sol
Labels: D3-trivial, not-breaking

#135 Feat/introduce obbligatory migration label
  .github/workflows/enforce-pr-labels.yml
  MIGRATION.md
Labels: D3-trivial, not-breaking, no-migration

#125 Clean up no longer needed scripts, tests and commands
  .github/workflows/demo-test.yml
  .github/workflows/deploy-vault.yml
  .github/workflows/register-vault-and-middleware.yml
  .github/workflows/test.yml
  Makefile
  README.md
  contract-addresses/dancelight.json
  contract-addresses/stagelight.json
  demos/DeployTanssiEcosystemDemo.s.sol
  deployment-docs/upgrade-docs/Dancelight.env
  deployment-docs/upgrade-docs/Stagelight.env
  script/DeployCollateral.s.sol
  script/DeployRewards.s.sol
  script/DeploySymbiotic.s.sol
  script/DeployTanssiEcosystem.s.sol
  script/DeployVault.s.sol
  script/HelperConfig.s.sol
  test/fork/Upgrades.t.sol
  test/fork/mainnet/Full.t.sol
  test/fork/mainnet/rewards_data.json
  test/fork/testnet/Middleware.t.sol
  test/integration/Full.t.sol
  test/integration/Middleware.t.sol
  test/integration/Rewards.t.sol
  test/unit/Deploy.t.sol
  test/unit/DeployProduction.t.sol
  upgrade-docs/Tanssi.env
Labels: D2-notlive, not-breaking, no-migration

#132 [MD-1212] - Optimize staker rewards to set the vault, instead of passing it through constructor
  MIGRATION.md
  demos/DeployTanssiEcosystemDemo.s.sol
  script/DeployProduction.s.sol
  script/DeployRewards.s.sol
  script/DeployTanssiEcosystem.s.sol
  src/contracts/middleware/Middleware.sol
  src/contracts/middleware/MiddlewareStorage.sol
  src/contracts/rewarder/ODefaultStakerRewards.sol
  src/contracts/rewarder/ODefaultStakerRewardsFactory.sol
  src/interfaces/rewarder/IODefaultStakerRewards.sol
  src/interfaces/rewarder/IODefaultStakerRewardsFactory.sol
  test/fork/Upgrades.t.sol
  test/fork/mainnet/Full.t.sol
  test/integration/Full.t.sol
  test/integration/Middleware.t.sol
  test/integration/Rewards.t.sol
  test/unit/Deploy.t.sol
  test/unit/Middleware.t.sol
  test/unit/Rewards.t.sol
Labels: breaking, D5-nicetohaveaudit⚠️, need-migration

#141 [MD-1183] Optimizes gas on checkUpkeep and prevents operators on too many vaults.
  src/contracts/middleware/Middleware.sol
  src/contracts/middleware/MiddlewareStorage.sol
  src/contracts/middleware/OBaseMiddlewareReader.sol
  src/interfaces/middleware/IMiddleware.sol
  src/interfaces/middleware/IOBaseMiddlewareReader.sol
  test/integration/Full.t.sol
  test/unit/Middleware.t.sol
Labels: D5-nicetohaveaudit⚠️, not-breaking, no-migration

#148 Adds custom claimRewards method on StakerRewards.
  src/contracts/rewarder/ODefaultStakerRewards.sol
  test/unit/Rewards.t.sol
Labels: D3-trivial, not-breaking, no-migration

#149 Removes legacy duplicated make command.
  Makefile
Labels: D3-trivial, not-breaking, no-migration

#156 Cleans unused imports and adds missing sections.
  src/contracts/extensions/OSharedVaults.sol
  src/contracts/middleware/Middleware.sol
  src/contracts/middleware/OBaseMiddlewareReader.sol
  src/contracts/rewarder/ODefaultOperatorRewards.sol
  src/contracts/rewarder/ODefaultStakerRewards.sol
  src/contracts/rewarder/ODefaultStakerRewardsFactory.sol
Labels: D3-trivial, not-breaking, no-migration

#151 Improves migration and adds changelog for v1.2.0.
  .gitignore
  CHANGELOG.md
  MIGRATION.md
  forge-cache/solidity-files-cache.json
  src/contracts/extensions/OSharedVaults.sol
  src/contracts/middleware/Middleware.sol
  src/contracts/middleware/OBaseMiddlewareReader.sol
  src/contracts/rewarder/ODefaultOperatorRewards.sol
  src/contracts/rewarder/ODefaultStakerRewards.sol
  src/contracts/rewarder/ODefaultStakerRewardsFactory.sol
Labels: D3-trivial, not-breaking, no-migration

#157 Uses right profile for demo CI task.
  .github/workflows/demo-test.yml
Labels: D3-trivial, not-breaking, no-migration

#163 Adds batchClaimRewards on OperatorRewards.
  src/contracts/rewarder/ODefaultOperatorRewards.sol
  src/contracts/rewarder/RewardsHintsBuilder.sol
  src/interfaces/rewarder/IODefaultOperatorRewards.sol
  test/integration/Full.t.sol
Labels: D3-trivial, not-breaking, no-migration

#165 Fixes reader address in dancelight.
  contract-addresses/dancelight.json
Labels: D3-trivial, not-breaking, no-migration

#166 Tests changing key and unpausing operator
  test/fork/mainnet/Full.t.sol
Labels: D3-trivial, not-breaking, no-migration
