Repository moondance-labs/tanssi-symbiotic, pull requests merged in 2025-05, with the labels that each got.

#88 [MD-1048] Run some basic static analyzers + [MD-972] Revisit integration tests to make sure we don't overprank
  script/DeployTanssiEcosystem.s.sol
  src/contracts/extensions/OSharedVaults.sol
  src/contracts/middleware/Middleware.sol
  src/contracts/middleware/MiddlewareStorage.sol
  src/contracts/middleware/OBaseMiddlewareReader.sol
  src/contracts/rewarder/ODefaultOperatorRewards.sol
  src/contracts/rewarder/ODefaultStakerRewards.sol
  src/interfaces/extensions/IOSharedVaults.sol
  src/interfaces/middleware/IOBaseMiddlewareReader.sol
  src/interfaces/rewarder/IODefaultOperatorRewards.sol
  src/interfaces/rewarder/IODefaultStakerRewards.sol
  test/integration/Full.sol
  test/integration/Middleware.t.sol
  test/unit/Deploy.t.sol
  test/unit/Middleware.t.sol
Labels: breaking, D3-trivial

#89 [MD-970] Testing upgrades in fork + [MD-1086] Fix fork tests in Sepolia
  .github/workflows/test.yml
  Makefile
  demos/DeployTanssiEcosystemDemo.s.sol
  script/DeployTanssiEcosystem.s.sol
  script/chain_data.json
  test/fork/Upgrades.t.sol
  test/unit/Deploy.t.sol
  test/unit/Rewards.t.sol
Labels: D3-trivial, not-breaking

#91 [L-13] Missing executeSlash() Call After requestSlash() for Veto Slashing
  foundry.toml
  src/contracts/middleware/Middleware.sol
  test/fork/Middleware.t.sol
  test/integration/Middleware.t.sol
Labels: D3-trivial, not-breaking

#93 Only distribute rewards to vaults with actual amount after distribution.
  src/contracts/rewarder/ODefaultOperatorRewards.sol
Labels: D5-nicetohaveaudit⚠️, not-breaking

#99 [L-16] Middleware may send bytes32(0) as validator key
  src/contracts/middleware/OBaseMiddlewareReader.sol
Labels: D5-nicetohaveaudit⚠️, not-breaking

#95 [L-03] operatorVaultPairs array length not adjusted
  src/contracts/middleware/OBaseMiddlewareReader.sol
  test/unit/Middleware.t.sol
Labels: D5-nicetohaveaudit⚠️, not-breaking

#96 [L-04] ClaimAdminFee() omits epoch in ClaimAdminFee event
  src/contracts/rewarder/ODefaultStakerRewards.sol
  src/interfaces/rewarder/IODefaultStakerRewards.sol
  test/unit/Rewards.t.sol
Labels: D5-nicetohaveaudit⚠️, not-breaking

#94 [L-01] getEpochAtTs() incorrect when timestamp matches epoch start
  src/contracts/middleware/OBaseMiddlewareReader.sol
  test/unit/Middleware.t.sol
Labels: D5-nicetohaveaudit⚠️, not-breaking

#100 Merge all issues to staging
  src/contracts/middleware/OBaseMiddlewareReader.sol
  src/contracts/rewarder/ODefaultOperatorRewards.sol
  src/contracts/rewarder/ODefaultStakerRewards.sol
  src/interfaces/rewarder/IODefaultStakerRewards.sol
  test/unit/Middleware.t.sol
  test/unit/Rewards.t.sol
Labels: D3-trivial, not-breaking

#103 Skips migration tests.
  Makefile
  script/DeployTanssiEcosystem.s.sol
  src/contracts/middleware/Middleware.sol
  test/fork/Upgrades.t.sol
Labels: D3-trivial, not-breaking

#104 [H-01] - Took out revert if not interval satisfied.
  src/contracts/middleware/Middleware.sol
  src/interfaces/middleware/IMiddleware.sol
  test/unit/Middleware.t.sol
Labels: D5-nicetohaveaudit⚠️, not-breaking

#101 Removes operator rewards migration code.
  Makefile
  script/DeployRewards.s.sol
  script/DeployTanssiEcosystem.s.sol
  src/contracts/middleware/Middleware.sol
  src/contracts/rewarder/ODefaultOperatorRewards.sol
  test/fork/Upgrades.t.sol
  test/mocks/previousVersions/IODefaultOperatorRewardsOld.sol
  test/mocks/previousVersions/ODefaultOperatorRewardsOld.sol
  test/unit/Rewards.t.sol
Labels: D3-trivial, not-breaking

#110 Mainnet Production Release
  Makefile
  script/DeployProduction.s.sol
  script/DeployRewards.s.sol
  script/DeployTanssiEcosystem.s.sol
  script/chain_data.json
  src/contracts/middleware/Middleware.sol
  src/contracts/rewarder/ODefaultOperatorRewards.sol
  test/fork/Upgrades.t.sol
  test/mocks/previousVersions/IODefaultOperatorRewardsOld.sol
  test/mocks/previousVersions/ODefaultOperatorRewardsOld.sol
  test/unit/DeployProduction.t.sol
  test/unit/Rewards.t.sol
  upgrade-docs/2025-05-19.md
  upgrade-docs/Dancelight.env
  upgrade-docs/Stagelight.env
Labels: D3-trivial, not-breaking

#109 [MD-1162] Link vault to collateral automatically on registration for operator specific vaults
  foundry.toml
  src/contracts/middleware/Middleware.sol
  test/integration/Full.t.sol
Labels: D3-trivial, not-breaking

#111 Ignores operators with power 0 when getting validator set.
  src/contracts/middleware/Middleware.sol
  src/contracts/middleware/OBaseMiddlewareReader.sol
  test/integration/Middleware.t.sol
  test/unit/Middleware.t.sol
Labels: D3-trivial, not-breaking
